version: '3.8'

services:
  # Zookeeper service
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"

  # Kafka service
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /kafka/logs

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # GraphQL Gateway
  gateway:
    build:
      context: ./gateway
    container_name: graphql-gateway
    ports:
      - "4000:4000"
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongodb:27017/gatewaydb
    depends_on:
      - kafka
      - mongodb

  # User Service
  user-service:
    build:
      context: ./services/user
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongodb:27017/userdb
    depends_on:
      - kafka
      - mongodb

  # Notification Service
  notification-service:
    build:
      context: ./services/notification
    container_name: notification-service
    ports:
      - "3002:3002"
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongodb:27017/notificationdb
    depends_on:
      - kafka
      - mongodb

volumes:
  mongo_data:
