version: "3.8"

services:
  graphql-gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    container_name: graphql-gateway
    ports:
      - "4000:4000"
    environment:
      USER_SERVICE_URL: http://user-service:3001/graphql
      NOTIFICATION_SERVICE_URL: http://notification-service:3002/graphql
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - user-service
      - notification-service
    networks:
      - backend

  user-service:
    build:
      context: ./services/user
      dockerfile: dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      MONGO_URI: ${USER_DB_URL}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - backend

  notification-service:
    build:
      context: ./services/notification
      dockerfile: dockerfile
    container_name: notification-service
    ports:
      - "3002:3002"
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      MONGO_URI: ${NOTIFICATION_DB_URL}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - backend

  sender-service:
    build:
      context: ./services/sender
      dockerfile: dockerfile
    container_name: sender-service
    ports:
      - "3003:3003"
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: your-email@gmail.com
      SMTP_PASS: your-app-specific-password
    networks:
      - backend

networks:
  backend:
    driver: bridge
